[package]
name = "assert_json"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
thiserror = "1.0"
codespan-reporting = "0.11"

[dev-dependencies]
indoc = "1.0"
strip-ansi-escapes = "0.1"